plugins { id 'com.android.application' }

android {
    namespace 'com.planora.app'
    compileSdk 35

    defaultConfig {
        applicationId 'com.planora.app'
        minSdk 23
        targetSdk 35
        versionCode 4
        versionName '1.3.0'
    }

    buildFeatures {
        buildConfig true
    }

    buildTypes {
        release { minifyEnabled false }
        debug { minifyEnabled false }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
